-- Custom Modular Hyprland Configuration (Extracted from hyprland_myown.lua)

require("config.colors")
require("config.variables")
require("config.autostart")
require("config.environment")
require("config.decorations")
require("config.animations")
require("config.inputs")
require("config.binds")
require("config.monitors")
require("config.workspaces")
require("config.rules")
require("config.plugins")
