general {
    lock_cmd = qs -p ~/.config/nexa/quickshell ipc call lockScreen lock
    before_sleep_cmd = qs -p ~/.config/nexa/quickshell ipc call lockScreen lock
    after_sleep_cmd = hyprctl dispatch dpms on

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# 1. Lock screen after 5 minutes of inactivity
listener {
    timeout = 300 
    on-timeout = qs -p ~/.config/nexa/quickshell ipc call lockScreen lock
}

# 2. Turn off display backlight after 10 minutes (safe for AMDGPU KMS)
listener {
    timeout = 600
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r && hyprctl dispatch dpms on
}

# 3. Suspend system after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
