[general]
bars = 32
framerate = 30

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000

# ; = 59
bar_delimiter = 59

# newline = 10
frame_delimiter = 10

[smoothing]
noise_reduction = 77
