color0 #52443d
color1 #ffb4ab
color2 #ffb595
color3 #e6bead
color4 #d2c78f
color5 #ffb595
color6 #e6bead
color7 #f1dfd8
color8 #a08d85
color9 #ffb4ab
color10 #ffb595
color11 #e6bead
color12 #d2c78f
color13 #ffb595
color14 #e6bead
color15 #f1dfd8

cursor                #f1dfd8
cursor_text_color     #1a110e
background            #1a110e
foreground            #f1dfd8
selection_foreground  #d8c2ba
selection_background  #52443d
active_border_color   #ffb595
inactive_border_color #52443d
url_color             #ffb595

active_tab_foreground   #542106
active_tab_background   #ffb595
inactive_tab_foreground #d8c2ba
inactive_tab_background #52443d
cursor_trail_color      #d8c2ba
